Add headless_mode_will_redirect filter
Shelob9/headless-mode pull request #15
Opened 2020-11-06 22:00 UTC by Shelob9

Fixes #14

## What Has Changed

New filter so I think I need so I can use WordPress/ PHP to respond to HTTP requests that are not for REST API, etc with a React app or whatever.

2021-02-15 20:42 UTC, Benunc commented
This PR looks simple enough, but i want to make sure I fully understand what's going on here, and how to test it before I merge it. 

Essentially the new filter defaults to 'true' and so unless a something is specifically filtering that value, all requests that make it to that point will redirect. To test it, I should add a code snippet to a site that filters the value of the new filter to `false` and then attempt to load the front end. 

I should also test by NOT filtering that value to ensure that it redirects correctly. 

@Shelob9 let me know if I am missing anything there.

2021-02-15 21:21 UTC, Benunc requested changes
Here's what I did to test:

1. set main `HEADLESS_MODE_CLIENT_URL` constant. This worked as expected.
2. wrote a custom function that returned "false" for the new `headless_mode_will_redirect` filter, no matter what. This worked as expected. 
3. Unset/commented out the main constant from step one, and removed my custom function from step 2. (simulating having installed the plugin but not set the constant yet.) This caused a whitescreen for any logged-out visitor. 
4. Re-enabled the function from step 2. This caused the redirect to stop working (because the value is false for the new filter) and made the white screen go away.

2021-02-15 21:21 UTC, Benunc commented on headless-mode.php
> +		if( apply_filters( 'headless_mode_will_redirect', true, $new_url ) ){
what if this value is not set/filtered? I'm getting a white screen (nothing in debug or query monitor) for the case of not having the main constant `HEADLESS_MODE_CLIENT_URL` set, using this code.

2021-03-06 19:26 UTC, Shelob9 commented on headless-mode.php
> +		if( apply_filters( 'headless_mode_will_redirect', true, $new_url ) ){
If that returns false, headless mode is disabled. You would return false when you wanted WordPress theme to render the page.

2021-03-06 21:40 UTC, Benunc commented on headless-mode.php
> +		if( apply_filters( 'headless_mode_will_redirect', true, $new_url ) ){
This appears to be unrelated to this PR, as I am getting a bug in a fresh install of the repo-version of the site. I am going to open a new issue with steps to replicate, and merge this one.

2021-03-06 21:40 UTC, merged

2021-03-06 21:41 UTC, Benunc reviewed
looks